# Generated by Django 4.2 on 2023-05-26 08:53

import cookbook.models
import cookbook.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='recipe',
            name='picture',
            field=models.ImageField(default='recipe/default.svg', storage=cookbook.storage.OverwriteStorage(), upload_to=cookbook.models.rename_file),
        ),
    ]
