# Generated by Django 4.2 on 2023-06-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0005_ingredient_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
