# Generated by Django 4.2 on 2023-05-16 15:25

import authentication.models
import cookbook.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='profile/default.svg', storage=cookbook.storage.OverwriteStorage(), upload_to=authentication.models.rename_file),
        ),
    ]
