# Generated by Django 4.2 on 2023-05-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresettoken',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
